Fix build without metadata support
Commit f36352dc4ece27fda24ef736183b8ff5729b8c96 introduced the parameter
pipe_timeout for the metadata config. If shairport-sync is now configured
without metadata support, the build fails with:

```
shairport.c: In function ‘main’:
shairport.c:766:9: error: ‘shairport_cfg {aka struct <anonymous>}’ has no member named ‘metadata_pipe_timeout’
   config.metadata_pipe_timeout = 5000; //milliseconds

```

Fix this by opting-out the affected code with CONFIG_METADATA.